---
- name: Ensure dnsmasq is installed.
  apt: name=dnsmasq state=present

- name: install basic packages
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - dnsmasq
    - tcpdump
    - tcptrack

- name: Create dnsmasq.conf.
  template:
    src: "dnsmasq.conf.j2"
    dest: "/etc/dnsmasq.conf"
    owner: root
    group: root
    mode: 0600
    backup: yes
  notify: restart dnsmasq
