---
- name: Create wpa_supplicant.conf.
  template:
    src: "wpa_supplicant.conf.j2"
    dest: "/etc/wpa_supplicant/wpa_supplicant.conf"
    owner: root
    group: root
    mode: 0600
  notify: reboot pi

- name: Add {{ wifi_acceess_eth_interface }}_1 to /etc/network/interfaces.d
  template:
    src: "eth0_1.j2"
    dest: "/etc/network/interfaces.d/{{ wifi_acceess_eth_interface }}_1"
    owner: root
    group: root
    mode: 0644
  notify: reboot pi

- name: Remove default gateway from /etc/dhcpcd.conf
  replace:
    dest: /etc/dhcpcd.conf
    regexp: '^static routers=10.2.78.1'
    replace: '#static routers=10.2.78.1'
